name: deploy-camarilla
on:
  push:
    branches: [master]

jobs:
  deploy:
   runs-on: ubuntu-latest
   steps:
    - name: Deploy Camarilla App
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        username: ${{secrets.SSH_USERNAME}}

        script:
          mkdir test
          cd test
          git clone git@github.com:brett-buskirk/camarilla.git
          echo "Deployment successful to Digital Ocean"
